#!/usr/bin/env python3

def ENDR(vlan, netS, mask, gate, netM, name):
  print("ENDR\n")
  print("spanning-tree vlan {} priority 0".format(vlan))
  print("ip access-list default_Vlan{}".format(vlan))
  print("10 permit ip 10.1.{}.0/{} any".format(netM,mask))
  print("route-map Vlan{} permit 10".format(vlan))
  print("  match ip address default_Vlan{}".format(vlan))
  print("  set ip default next-hop 129.82.10.181\n")
  print("interface Vlan{}".format(vlan))
  print("no ip redirects")
  print("ip address 10.1.{}.2/{}".format(netS,mask))
  print("ip router ospf 1 area 0.0.0.0")
  print("ip pim sparse-mode")
  print("ip policy route-map Vlan{}".format(vlan))
  print("hsrp version 2")
  print("hsrp {}".format(vlan))
  print("  preempt delay minimum 180")
  print("  priority 250")
  print("  timers  1  3")
  print("  ip 10.1.{}.1".format(gate))
  print("  description {}".format(name))
  print("  no shutdown")

def DREN(vlan, netS, mask, gate, netM, name):
  print("DREN\n")
  print("spanning-tree vlan {} priority 0".format(vlan))
  print("ip access-list default_Vlan{}".format(vlan))
  print("10 permit ip 10.1.{}.0/{} any".format(netM,mask))
  print("route-map Vlan{} permit 10".format(vlan))
  print("  match ip address default_Vlan{}".format(vlan))
  print("  set ip default next-hop 129.82.10.181\n")
  print("interface Vlan{}".format(vlan))
  print("no ip redirects")
  print("ip address 10.1.{}.3/{}".format(netS,mask))
  print("ip router ospf 1 area 0.0.0.0")
  print("ip pim sparse-mode")
  print("ip policy route-map Vlan{}".format(vlan))
  print("hsrp version 2")
  print("hsrp {}".format(vlan))
  print("  preempt delay minimum 180")
  print("  priority 110")
  print("  timers  1  3")
  print("  ip 10.1.{}.1".format(gate))
  print("  description {}_Private".format(name))
  print("  no shutdown")

if __name__ == "__main__":
  vlan = netS = mask = gate =netM = -1
  while vlan < 0:
    try:
      vlan=int(input('Enter vlan: '))
      netS=int(input('Enter subnet: '))
      mask=int(input('Enter mask: '))
      gate=int(input('Enter gateway address: '))
      netM=int(input('Enter network: '))
      name=str(input('Enter building name: '))
    except ValueError:
      print ("Incorrect data type.")
  print("----------------------------------")
  ENDR(vlan, netS, mask, gate, netM, name)
  print("----------------------------------")
  DREN(vlan, netS, mask, gate, netM, name)
  print("----------------------------------")
