name: Test Gooop Package

on:
  push:
    paths:
      - 'src/gooop/**'
      - '.github/workflows/test_gooop.yml'
  pull_request:
    paths:
      - 'src/gooop/**'
      - '.github/workflows/test_gooop.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/gooop
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Install protoc
        run: |
          sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Generate protobuf files
        run: |
          protoc --python_out=./gooop ./proto/*.proto
      - name: Run tests
        run: poetry run pytest
