name: Test Monk Package

on:
  push:
    paths:
      - 'src/monk/**'
      - '.github/workflows/test_monk.yml'
  pull_request:
    paths:
      - 'src/monk/**'
      - '.github/workflows/test_monk.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/monk
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run tests
        run: poetry run pytest
